{% set name = "gooseslurm" %}
{% set version = "0.3.1" %}
{% set sha256 = "f3e197e3d7d201c9923cc4506ee32cd5f9f1bba1a82205489efc155f4e0230ec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseSLURM/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py<35]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - Gdel = GooseSLURM.cli.Gdel:main
    - Ginfo = GooseSLURM.cli.Ginfo:main
    - Gps = GooseSLURM.cli.Gps:main
    - Gstat = GooseSLURM.cli.Gstat:main
    - Gsub = GooseSLURM.cli.Gsub:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docopt
    - click
    - tqdm
    - pyyaml

test:
  imports:
    - GooseSLURM
  commands:
    - Gdel --help
    - Ginfo --help
    - Gps --help
    - Gstat --help
    - Gsub --help

about:
  home: https://github.com/tdegeus/GooseSLURM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SLURM command line tools and scripts.
  description: SLURM command line tools and scripts.
  doc_url: https://github.com/tdegeus/GooseSLURM
  dev_url: https://github.com/tdegeus/GooseSLURM

extra:
  recipe-maintainers:
    - tdegeus
