{% set name = "GooseSLURM" %}
{% set org = "tdegeus" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d42620eae86a2ae40b57082fc748aa3673939e3a112a0b8253dc063cf9db90f

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - Gdel = {{ name }}.cli.Gdel:main
    - Ginfo = {{ name }}.cli.Ginfo:main
    - Gps = {{ name }}.cli.Gps:main
    - Gstat = {{ name }}.cli.Gstat:main
    - Gsub = {{ name }}.cli.Gsub:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - click
    - docopt
    - numpy
    - python >=3.6
    - pyyaml
    - tqdm

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "import {{ name }}; assert {{ name }}.version == '{{ version }}'"
    - Gdel --version | grep {{ version }}
    - Ginfo --version | grep {{ version }}
    - Gps --version | grep {{ version }}
    - Gstat --version | grep {{ version }}
    - Gsub --version | grep {{ version }}
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SLURM command line tools and scripts.
  description: SLURM command line tools and scripts.
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
