{% set version = "0.13.4" %}

package:
  name: gooseslurm
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseSLURM/archive/v{{ version }}.tar.gz
  sha256: cf33854158f74da3b5496763c538714445805ae545ccf80fd5970db0f9438f4d

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - Gdel = GooseSLURM.cli_Gdel:main
    - Ginfo = GooseSLURM.cli_Ginfo:main
    - Gps = GooseSLURM.cli_Gps:main
    - Gstat = GooseSLURM.cli_Gstat:main
    - Gsub = GooseSLURM.cli_Gsub:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - click
    - numpy
    - python >=3.6
    - pyyaml
    - tqdm
    - typing_extensions

test:
  imports:
    - GooseSLURM
  commands:
    - pip check
    - python -c "import GooseSLURM; assert GooseSLURM.version == '{{ version }}'"
    - Gdel --version | grep {{ version }}
    - Ginfo --version | grep {{ version }}
    - Gps --version | grep {{ version }}
    - Gstat --version | grep {{ version }}
    - Gsub --version | grep {{ version }}
  requires:
    - pip

about:
  home: https://github.com/tdegeus/GooseSLURM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SLURM command line tools and scripts.
  description: SLURM command line tools and scripts.
  doc_url: https://github.com/tdegeus/GooseSLURM
  dev_url: https://github.com/tdegeus/GooseSLURM

extra:
  recipe-maintainers:
    - tdegeus
