{% set name = "GooseSLURM" %}
{% set org = "tdegeus" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b1cab65ad4f0b5d7ad6838d89491acf01ef76a0cf82a386518e5fa7d176aeefa

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - Gdel = {{ name }}.cli.Gdel:main
    - Ginfo = {{ name }}.cli.Ginfo:main
    - Gps = {{ name }}.cli.Gps:main
    - Gstat = {{ name }}.cli.Gstat:main
    - Gsub = {{ name }}.cli.Gsub:main

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - click
    - docopt
    - python
    - pyyaml
    - tqdm

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "import {{ name }}; print({{ name }}.version)"
    - Gdel --version
    - Ginfo --version
    - Gps --version
    - Gstat --version
    - Gsub --version
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SLURM command line tools and scripts.
  description: SLURM command line tools and scripts.
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
