{% set name = "GooseSLURM" %}
{% set org = "tdegeus" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1f52cfba3ff1f3122243c0fc0cfe1b5dfa049f35865da95e0a0385d926a4b8d1

build:
  number: 0
  skip: true  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - Gdel = {{ name }}.cli.Gdel:main
    - Ginfo = {{ name }}.cli.Ginfo:main
    - Gps = {{ name }}.cli.Gps:main
    - Gstat = {{ name }}.cli.Gstat:main
    - Gsub = {{ name }}.cli.Gsub:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - docopt
    - click
    - tqdm
    - pyyaml

test:
  imports:
    - {{ name }}
  commands:
    - Gdel --help
    - Ginfo --help
    - Gps --help
    - Gstat --help
    - Gsub --help

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SLURM command line tools and scripts.
  description: SLURM command line tools and scripts.
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
