{% set name = "GooseSLURM" %}
{% set org = "tdegeus" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 447703489be5cb95323304c7a905fcf4034d289fd7e71a3fecf387348754c130

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - Gdel = {{ name }}.cli.Gdel:main
    - Ginfo = {{ name }}.cli.Ginfo:main
    - Gps = {{ name }}.cli.Gps:main
    - Gstat = {{ name }}.cli.Gstat:main
    - Gsub = {{ name }}.cli.Gsub:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - click
    - docopt
    - python >=3.6
    - pyyaml
    - tqdm

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "import {{ name }}; print({{ name }}.version)"
    - Gdel --version
    - Ginfo --version
    - Gps --version
    - Gstat --version
    - Gsub --version
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SLURM command line tools and scripts.
  description: SLURM command line tools and scripts.
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
